name: Deploy application to Heroku

on:
  workflow_run:
    workflows: ["Run tests with Gradle"]
    branches: [ master ]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pregnancy-roulette"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
