name: Check deployment status

on: deployment_status

jobs:

  deployment-status:
    if: github.event.deployment_status.state != 'pending'
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.0.23
        env:
          GITHUB_TOKEN: ${{secrets.REPOSITORY_ACCESS_TOKEN}}
        with:
          route: POST /repos/:repository/statuses/${{github.event.deployment.sha}}
          repository: ${{github.repository}}
          state: ${{github.event.deployment_status.state}}
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          description: >
            ${{format('Heroku deployment is {0}', github.event.deployment_status.state)}}
          context: deployment-status

  health-check:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - id: health_check
        uses: jtalk/url-health-check-action@v1.3
        with:
          url: ${{github.event.deployment.payload.web_url}}
          follow-redirect: true
          max-attempts: 4
          retry-delay: 30s
        continue-on-error: true
      - uses: octokit/request-action@v2.0.23
        env:
          GITHUB_TOKEN: ${{secrets.REPOSITORY_ACCESS_TOKEN}}
        with:
          route: POST /repos/:repository/statuses/${{github.event.deployment.sha}}
          repository: ${{github.repository}}
          state: ${{steps.health_check.outcome}}
          target_url: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
          description: >
            ${{format('Site health is {0}', steps.health_check.outcome)}}
          context: health-check